### ISSUE TITLE
[BUG] Something Broke on Classic

### ISSUE THREAD

**Issue by Gogo1951** [arkayenro/arkinventory#1512] opened 2021-08-24 15:30 UTC
![image](https://user-images.githubusercontent.com/55365231/130645527-2abec45e-f8d2-407b-b17a-317f9f716f5a.png)

![image](https://user-images.githubusercontent.com/55365231/130645489-3dd0d338-5c93-46c5-9a03-9396bedcaeea.png)

-[Announcer]- Announcements: [true] 
-[Announcer]- taunt: [false] 
ArkInventory: Loading Connected Realm (US) Data 
 Loaded: LFG Bulletin Board 2.59 by Vyscî-Whitemane 
Raid Buff Tracker only works for Druids, Mages, and Priests. 
 Loaded: RollTracker Classic Z 1.1.3 by GPI / Erytheia-Razorfen / Zolerii / Roadblock 
WeakAuras:  There are 1 updates to your auras ready to be installed! 
ArkInventory: v30955.15 (Alpha) [The Burning Crusade] Enabled 
ArkInventory: Rules Enabled 
[Attune] v241 by Cixi@Remulos. Type /attune to start. 
 Welcome to ElvUI TBC version 2.12, type /ec to access the in-game configuration menu. If you are in need of technical support you can visit us at [https://www.tukui.org] or join our Discord: [https://discord.gg/xFWcfgE]  
 Please use /ehelp for a list of available ElvUI commands. 
 ArkInventory: Successful rule registration from Pawn - rule function [pawnupgrade] is now active 
 ArkInventory: Successful rule registration from Pawn - rule function [pawnnotupgrade] is now active 
 ThreatClassic2 v2.38 - Type /tc2 for options. 
 Restocker: Loaded 
 GogoLoot : Due to a recent Blizzard API change, you may occasionally see a Loot Window if you attempt loot while in combat. Sorry! 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: English (US) translations - attempt 1 of 5. 
 ArkInventory: English (US) translations successfully loaded. 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: Rules: Outfitter Enabled 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 TSM: Sold [Strange Dust]x4 for 36s 83c to Lachingspace 
 TSM: Sold [Strange Dust]x5 for 46s 03c to Lachingspace 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 TSM: Sold [Black Pearl]x1 for 98s 79c to Sinafeyurden 
 TSM: Sold [Formula: Enchant Weapon - Minor Beastslayer]x1 for 59s 85c to Synodic 
 TSM: Sold [Major Healing Potion]x1 for 32s 10c to Demonseeds 
 TSM: Sold [Major Healing Potion]x1 for 32s 10c to Demonseeds 
 TSM: Sold [Major Healing Potion]x1 for 32s 10c to Demonseeds 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 TSM: Sold [Major Healing Potion]x1 for 32s 10c to Demonseeds 
 TSM: Sold [Major Healing Potion]x1 for 32s 10c to Demonseeds 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 TSM: Sold [Major Healing Potion]x1 for 32s 10c to Demonseeds 
 TSM: Sold [Major Healing Potion]x1 for 32s 10c to Demonseeds 
 TSM: Sold [Major Healing Potion]x1 for 32s 10c to Demonseeds 
 TSM: Sold [Major Healing Potion]x1 for 32s 10c to Demonseeds 
 TSM: Sold [Major Healing Potion]x1 for 32s 10c to Demonseeds 
 TSM: Sold [Arcane Dust]x2 for 2g 08s 97c to Cnormanp 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 TSM: Sold [Vilebranch Coin]x1 for 9s 87c to Vickk 
 TSM: Sold [Feral Cloak of Intellect]x1 for 1g 26s 59c to Phoqueboi 
 TSM: Sold [Excavator's Brand]x1 for 56g 81s 94c to Apõcalypse 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 TSM: Sold [Lesser Mystic Essence]x1 for 8s 18c to Cocainus 
 You receive item: [Murphstar of Power]. 
 TSM: Horde Auction House sent you a message: Auction expired: Murphstar of Power 
 You receive item: [Lesser Healing Potion]. 
 TSM: Horde Auction House sent you a message: Auction expired: Lesser Healing Potion 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 You receive item: [Lesser Healing Potion]. 
 TSM: Horde Auction House sent you a message: Auction expired: Lesser Healing Potion 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 You receive item: [Giant Club of the Tiger]. 
 TSM: Horde Auction House sent you a message: Auction expired: Giant Club of the Tiger 
 You receive item: [Deckhand's Shirt]. 
 TSM: Horde Auction House sent you a message: Auction expired: Deckhand's Shirt 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 You receive item: [Deckhand's Shirt]. 
 TSM: Horde Auction House sent you a message: Auction expired: Deckhand's Shirt 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 TSM: Sold [Mighty Rage Potion]x1 for 3g 47s 58c to Jagerbum 
 TSM: Sold [Mighty Rage Potion]x1 for 3g 47s 58c to Jagerbum 
 TSM: Total Gold Collected: 73g 27s 98c 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value) 
 ArkInventory: ERROR> Interface\AddOns\ArkInventory\ArkInventoryClient.lua:10: attempt to call field 'IsAnimaItemByID' (a nil value)

**Comment by wirerydr** [comment] 2021-08-24 16:26
Same error here.  worked fine late night yesterday, prior to today's maintenance downtime.  Unrelated to ElvUI, ThreatClassic, Restocker, GogoLoot and Raid Buff Tracker - I don't run those addons.

**Comment by Xalcon** [comment] 2021-08-24 19:55
For a temporary fix, open `ArkInventoryClient.lua` and replace line 8
```
if C_Item then
```
with
```
if C_Item and C_Item.IsAnimaItemByID then
```

The issue is, `C_Item` does exist on classic (tbc) but `IsAnimaItemByID` is a shadowlands function. The check for the actual function is missing though.

**Comment by wirerydr** [comment] 2021-08-24 20:31
> 
> 
> For a temporary fix, open `ArkInventoryClient.lua` and replace line 8
> 
> ```
> if C_Item then
> ```
> 
> with
> 
> ```
> if C_Item and C_Item.IsAnimaItemByID then
> ```
> 
> The issue is, `C_Item` does exist on classic (tbc) but `IsAnimaItemByID` is a shadowlands function. The check for the actual function is missing though.

Confirmed that the edit @Xalcon proposes clears the error - thank you very much for that.

**Comment by arkayenro** [comment] 2021-08-24 22:36
fixed in [alpha 16](https://www.curseforge.com/wow/addons/ark-inventory/files/3438156)

**Closed** 2021-08-25 13:51 UTC
