### ISSUE TITLE
World Map constantly changing back to current Zone since 7.3.5

### ISSUE THREAD

**Issue by schiry** [arkayenro/arkinventory#990] opened 2018-01-22 21:58 UTC
I am having this issue that when I open the world map and zoom out of the current zone or change the zone with the drop down menu. 
It always takes about 1-2 seconds and I am back to the Zone I'm in.
I am also not sure if it is really Arkinventory which is causing this issue but simply disabling it fixes the problem, so I thought posting it here would be a good idea.
I don't know if this helps, but I have attached a .txt with a list of all my other addons
[addons.txt](https://github.com/arkayenro/arkinventory/files/1653722/addons.txt)

**Comment by NHDriver4** [comment] 2018-01-24 00:57
This is a conflict between CollectMe and ArkInventory. I've been having the same issues for the past week or so and finally took the time to narrow it down @arkayenro 

ArkInventory 3.07.39 - 1/21/2018
CollectMe v2.9.5 - 10/29/2017

**Comment by NHDriver4** [comment] 2018-01-24 01:00
https://wow.curseforge.com/projects/collect_me/issues/90

**Comment by arkayenro** [comment] 2018-01-24 03:26
i cant see an obvious conflict

i disabled all the zone change stuff back in 3.07.29 as it was being annoying. so while AI still listens for the event it doesnt actually do anything when notified.  are you using an older version?

collect_me does update the map after every zone change (via its ldb object) but that looks normal

**Comment by NHDriver4** [comment] 2018-01-24 03:34
I am using the versions above. With just BOTH Ark and CollectMe, it happens. If one of the two are running, there's no issue.

**Comment by arkayenro** [comment] 2018-01-24 03:53
theres an alpha version of 3.07.40 that has debug output in it on wowace/curseforge here  https://www.wowace.com/projects/ark-inventory/files/2523547/download

install that and start the game
go into the AI config and enable debug

walk in and out of the dalaran bank
* when you walk in you should get zone_changed_indoors and no map update (you cant fly there so it wont check)
* when you walk out you should get zone_changed and a map set output

repeat with the map open (in minimum mode)
* walking in should be the same
* walking out should show the zone change but should not update the map

does that happen for you like that?

outside the bank (anywhere you can fly)
open the map
change the dropdown to another zone (i presume thats all youre doing? then wait 5-10 seconds)

is there any debug output from AI? zone change or map set?

**Comment by NHDriver4** [comment] 2018-01-24 04:25
Thanks. I updated and preformed your steps.

After enabling debug, I do see the messages that you indicated while moving in and out of zones, bank, city, etc. Using the drop down and changing the map manually and waiting does not trigger any output. Moving into another zone does not cause the map to change.

As soon as I turn on CollectMe, the map (every 2-3 seconds) defaults back to the zone that I am in. There is no debug output from Ark while that is happening. Again, this only happens when both Ark and CollectMe are running.

**Comment by arkayenro** [comment] 2018-01-24 07:13
ok so if theres absolutely no output from AI then there are no zone changes being triggered, nor is AI setting the map to the current zone. so somehow collect_me is getting triggered but only with AI running.

i might download it and see if i can work it out

**Comment by arkayenro** [comment] 2018-01-24 07:18
looks like something in the LDB object, if you mouse over it the data goes away, just like the map

**Comment by arkayenro** [comment] 2018-01-24 07:28
actually its the TOYS_UPDATED event, it keeps triggering every 2 seconds when AI is loaded, which triggers an update in collect_me, which resets the map - they probably should add a check if the map is opened to just check later

and i need to check what AI is doing thats triggering a toybox update

**Comment by Mindlessgalaxy** [comment] 2018-01-24 08:09
Hi,

I also want to say thank you so much for looking into this as it is driving me nuts and I love using your add on and have done for so long I cannot play the game without it.  I was also of the understanding this was a Collect me issue, but having said that I have no idea about Lua coding etc.  I did want to say thank you for putting in the extra yards just to work out where the problem is exactly and now I hope the author of Collect Me is able to correct this.  I have posted to his website as have many others with no response?  I just assumed he is also playing and trying to fix several issues at the same time.  But awesome to see you get involved and it means a lot to all of us who appreciate all you do for us and always responding so quickly and as best you can to issues, whether or not your add on.

Thanks again and have a lovely day/night.

**Comment by Mindlessgalaxy** [comment] 2018-01-24 09:22
Hi Again,

Whatever you did with the Alpha version has fixed the problem up for me. Thank you so so much for doing that and taking the time to help us out.  Everything else appears to be working well as well with no errors so far :).

Thanks heaps :)

**Comment by arkayenro** [comment] 2018-01-24 12:47
toy scanning should be properly fixed in the [r688-alpha](https://www.wowace.com/projects/ark-inventory/files/2523664/download) if you want to test that with collect_me

pet and heirloom data might stay empty if you clear all your account data in AI so please dont until i get them fixed as well

**Comment by Mindlessgalaxy** [comment] 2018-01-24 15:24
So far so good and doing exactly as you have requested.  Again I cannot thank you enough for your help.

One issue I have since and I am not sure if related?  When I log off from one toon onto another the game hangs 3/4 of the way into loading and then crashes.  I do a control-alt-delete and log in and fine. It has only happened since I have done these  updates, but I think it is just coincidence and nothing else, although I thought I better let you know.

Thanks heaps.

**Comment by schiry** [comment] 2018-01-24 18:34
Hi, thank you so much for looking into this issue so quickly. You are my heroes.
As I don't understand much of addon development I just installed the alpha mentioned above and it works for me like a charm. It is really cool to see that you care so much about this and get so involved with the users.

Thanks very much from Germany and kind regards.

**Comment by NHDriver4** [comment] 2018-01-24 21:17
Great news! I will check it out when I get home. Thanks again @arkayenro. 

Do you have a patron or donation link?

**Comment by arkayenro** [comment] 2018-01-24 22:29
if youve downloaded a previous alpha for the toybox issue please make sure you download this one, [r690-alpha](https://www.wowace.com/projects/ark-inventory/files/2523854/download), as the other collection scanning code has been fixed to work the same way so should make them more stable

**Comment by NHDriver4** [comment] 2018-01-25 00:23
The latest alpha that you published r690 plays well with CollectMe once again. Thanks again!

**Comment by arkayenro** [comment] 2018-02-12 12:59
fixed in 3.07.40

**Closed by arkayenro** 2018-02-12 12:59 UTC
Labels: bug
