### ISSUE TITLE
Issues with Item Age

### ISSUE THREAD

**Issue by Lesyde** [arkayenro/arkinventory#804] opened 2016-07-28 21:03 UTC
For some items the itemage is set to 0 at every login. 
I have tried everything in configuration/restacking including reset save variables.

Can i test anything else or what information do you need for investigation?

Thank you for your wunderful addon.
Regards Lesyde

**Comment by arkayenro** [comment] 2016-07-30 07:25
which items?
which location?
what type of bag is it in?
if you move them to another bag does it still happen?

**Comment by Lesyde** [comment] 2016-07-31 11:54
Hi,
moving items between bags change nothing.
Attached some screenshots

**Comment by Lesyde** [comment] 2016-08-13 20:03
What informations do you need?
Can i test something?

**Comment by richardfein** [comment] 2016-08-14 11:28
Also have the exact same issue with item age. 
![image](https://cloud.githubusercontent.com/assets/10539411/17648799/96e59ed2-61f0-11e6-933d-9fbee98b1654.png)

**Comment by arkayenro** [comment] 2016-08-15 13:51
found the cause, will be fixed in 30705

**Comment by Lesyde** [comment] 2016-08-22 19:02
It work. Thanks.

**Closed** 2016-08-23 03:28 UTC
Labels: bug

**Comment by richardfein** [comment] 2016-08-27 04:29
This is fixed for me on some characters but not others - see screenshot. 
![image](https://cloud.githubusercontent.com/assets/10539411/18025128/5096b75c-6bed-11e6-8ef0-7a7189fb4e0c.png)

**Comment by Lesyde** [comment] 2016-09-27 19:02
It's look like v 3.07.13 has the same problem with some items.
