### ISSUE TITLE
[BUG] Recent update broke the addon in WOLK

### ISSUE THREAD

**Issue by cwland** [arkayenro/arkinventory#1591] opened 2022-09-02 22:37 UTC
**What version number you are using?**

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
WOLK prepatch

**What language is the game client set to?**
english

**Describe the bug**
Bags won't open when the game loads

**To Reproduce**
install the latest version of the addon 

**Screenshots**

**Additional context**
Date: 2022-09-02 16:32:28
ID: 1
Error occured in: Global
Count: 5
Message: ..\AddOns\ArkInventory\Core\ArkInventory.lua line 6681:
   CreateFrame(): Couldn't find inherited node "ARKINV_TemplateButtonItem1"
Debug:
   [string "=[C]"]: CreateFrame()
   [string "@ArkInventory\Core\ArkInventory.lua"]:6681: Frame_Bag_OnLoad()
   [string "*:OnLoad"]:1:
      [string "*:OnLoad"]:1
   [string "=[C]"]: CreateFrame()
   [string "@ArkInventory\Core\ArkInventory.lua"]:5667: Frame_Container_OnLoad()
   [string "*:OnLoad"]:1:
      [string "*:OnLoad"]:1
Locals:
(*temporary) = "ItemButton"
(*temporary) = "ARKINV_Frame1ScrollContainerBag1Item1"
(*temporary) = ARKINV_Frame1ScrollContainerBag1 {
 0 = <userdata>
 ARK_Data = <table> {
 }
}
(*temporary) = "ARKINV_TemplateButtonItem1"

AddOns:
  Swatter, v2.5.6773 (SwimmingSeadragon)
  ArkInventory, v30967.1
  Outfitter, v2.0.4
  Scrap, v9.1.2
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=90)

**Comment by arkayenro** [comment] 2022-09-03 01:35
#1590

**Comment by arkayenro** [comment] 2022-09-03 06:32
Duplicate of #1590

**Closed** 2022-09-03 06:33 UTC
Labels: blizzard, wrath
