### ISSUE TITLE
TSM addon conflict when viewing "in box" mail.

### ISSUE THREAD

**Issue by NuubEitrigg** [arkayenro/arkinventory#1071] opened 2018-07-31 23:34 UTC
With Arkinventory and TradeSkillMaster addons installed, when I open the mailbox to inbox page, the incoming mails are not visible. There are no lua errors.

**Comment by arkayenro** [comment] 2018-08-01 02:00
duplicate of #1063

**Closed** 2018-08-01 02:04 UTC
