### ISSUE TITLE
Incorrect behaviour when look at other characters bags.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arkayenro/arkinventory#619] opened 2015-03-20 04:25 UTC
```
Downloaded from > googlecode | wowinterface | curse | wowui | other (specify)


What steps will reproduce the problem?
1. If I use the switch character option, I am only able to see the some of the 
items. The bag space shows 14/16, so it seems to only show one bag instead of 
them all.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
r406

Please provide any additional information below.


```

Original issue reported on code.google.com by `DrGjerde...@gmail.com` on 19 Aug 2013 at 6:07

**Comment by spiralofhope** [comment] 2015-10-12 08:41
This is a duplicate of #697

**Comment by arkayenro** [comment] 2016-07-07 10:45
closing old issues - if its still a problem re-open the ticket

**Closed by arkayenro** 2016-07-07 10:45 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
