### ISSUE TITLE
[BUG] Arkinventory minimizes the main currencies tab

### ISSUE THREAD

**Issue by Cabro** [arkayenro/arkinventory#1857] opened 2024-01-20 21:03 UTC
**What version number you are using?**
31023 wrath

**What game client are you playing? Retail, Wrath, Classic / Live, PTR, Beta**
Wrath

**What language is the game client set to?**
enUS

**Describe the bug**
The currency tab for "Dungeons and Raid" will be automatically collapsed after opening the currency tab a few times.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Open the currency tab (press C, click currency). Do this a few times. You will see the Dungeon and Raid to be automatically collapsed after a few opens. This is only happening with Arkinventory installed. Without it this does not happen. It was very annoying to pinpoint, but it is due to Arkinventory 100%.

**Screenshots**
![image](https://github.com/arkayenro/arkinventory/assets/1155017/5dbda81e-6ce5-470f-a729-ee7f9861326c)

**Additional context**
This is creating unnecessary clicks needed to see something that is visible by default without any addons. Instead of QoL improvement, the addon brings grief for this section.
Somehow it is remembering the state of the tab if you click it manually, and it will not collapse it (for verifying and testing purposes). But after a fresh login, the bug just happens.

**Comment by Hasselshoff** [comment] 2024-02-17 23:13
I am also experiencing this, not a big deal, but I did find it strange!  I never isolated the issue to the ArkInventory addon or its auxiliaries though, but it's interesting that this poster has.  I will test my own to verify & update this thread.

**Comment by arkayenro** [comment] 2024-02-18 12:18
i havent had a chance to look into it yet but arkinventory expands all the categories, checks, and then restores it back to how it was before it checked.  if you open the window it will abort that restore process so if anything it should get stuck with them expanded, not collapsed.

i dont play wrath so dont have any dungeon/raid currencies but its the same code across all versions so should happen in retail as well.

**Comment by Cabro** [comment] 2024-03-29 15:13
I have stopped using Arkinventory soon after i opened this bug report. This behaviour hasn't repeated without the addon. It's 100% this addon.

**Comment by Ragedaug** [comment] 2024-04-25 15:12
Just to add my 2 cents, I was checked all public versions from November to current and found the currency bug occurs here:

The behavior starts in: 
3.10.19.alpha-4   12/9/23

It's fixed in:
3.10.21.alpha-3   12/25/23 

The returns in:
3.10.22.alpha-1   1/14/24

The Dungeon & Raid Currencies will collapse randomly when I reload, login, or zone in to an instance. So to say, it doesn't happen every time, but within 3-4 of the events above, it will happen.

The reason this is a pain point is because I have my currencies viewable in my titan panel, with a mouse over, but when Ark collapses the top section, I can't see them, then have to go through all the steps to expand the section before they are viewable, but that only lasts until I load or reload. then I have to do it again.

**Comment by Ragedaug** [comment] 2024-04-25 15:33
> i havent had a chance to look into it yet but arkinventory expands all the categories, checks, and then restores it back to how it was before it checked. if you open the window it will abort that restore process so if anything it should get stuck with them expanded, not collapsed.
> 
> i dont play wrath so dont have any dungeon/raid currencies but its the same code across all versions so should happen in retail as well.

It's definitely interesting. In Retail, we have several sections in the currency tab, including "Dungeon and Raid", and Ark is not collapsing any of them. Which is the same behavior last seen in Wrath at 3.10.22 (R). When I update Wrath's addon to current to match Ark that I'm running in Retail, it starts collapsing the Dungeon and Raid currency section.

Steps to Reproduce:

1. Log into the game with Arkinventory at version 3.10.22 (R) and verify no issues, all currency sections expanded.
2. Update Arkinventory from 3.10.22 (R) to 3.10.27-alpha-11
3. Type /reload the game.  -- when I recreated this time, I had to /reload twice for the section collapse to occur. 

I have disabled all other addons as well to ensure this is something between Arkinventory and Blizzard going on here. 

I continue to use Arkinventory, but typically leave it at 3.10.19.alpha-3, because the currency tab isn't affected and that's before the "GetCurrencyListLink" error starts occurring.

**Comment by arkayenro** [comment] 2024-04-25 23:05
could you run this in wrath, i dont have any currencies there

/dump ArkInventory.CrossClient.GetCurrencyListInfo( 1 )

mostly i need to know if its isExpanded or isHeaderExpanded - looks like they changed one of the return names

**Comment by arkayenro** [comment] 2024-04-25 23:42
i think i may have found the issue.  should be fixed in the next alpha

**Comment by Ragedaug** [comment] 2024-04-25 23:43
I'm running the commands currently, would you still like the output?

**Comment by arkayenro** [comment] 2024-04-25 23:47
yes please

**Comment by Ragedaug** [comment] 2024-04-25 23:52
/dump GetCurrencyListInfo(1)

_With Section Expanded:_
```
Dump: value=GetCurrencyListInfo(1)
[1]="Dungeon and Raid",
[2]=true,
[3]=true,
[4]=false,
[5]=false
```

_With Section Collapsed:_
```
Dump: value=GetCurrencyListInfo(1)
[1]="Dungeon and Raid",
[2]=true,
[3]=false,
[4]=false,
[5]=false
```

############################################################
/dump ArkInventory.CrossClient.GetCurrencyListInfo(1)

_With Section Expanded:_ 
```
Dump: value=ArkInventory.CrossClient.GetCurrencyListInfo(1)
[1]={
 isHeader=true,
 name="Dungeon and Raid",
 isTypeUnused=false,
 isHeaderExpanded=true,
 isShownInBackpack=flase
}
```

_With Section Collapsed_
```
Dump: value=ArkInventory.CrossClient.GetCurrencyListInfo(1)
[1]={
 isHeader=true,
 name="Dungeon and Raid",
 isTypeUnused=false,
 isHeaderExpanded=false,
 isShownInBackpack=flase
}
```

**Comment by arkayenro** [comment] 2024-04-25 23:55
ok, good, i'd already catered for the return mismatch but wasnt sure.  it likes it was probably the other thing i found (header expansion changed from 0/1 to false/true)

**Comment by arkayenro** [comment] 2024-04-26 04:05
try [3.10.27-alpha-13](https://www.curseforge.com/wow/addons/ark-inventory/files/5292138)

**Comment by Ragedaug** [comment] 2024-04-27 15:39
So far, working like a champ. thanks Arkayenro!!

**Closed** 2024-04-28 21:40 UTC
