### ISSUE TITLE
[BUG] Wrath inventory not refreshing, missing items throwing errors on mouseover

### ISSUE THREAD

**Issue by falcon1209** [arkayenro/arkinventory#1827] opened 2023-10-10 17:56 UTC
3.10.17

Wrath

English

**Logging into a character produces the following:**

Message: Interface/AddOns/ArkInventory/Core/ArkInventory.lua:11641: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Oct 10 12:52:59 2023
Count: 1
Stack: Interface/AddOns/ArkInventory/Core/ArkInventory.lua:11641: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua"]:210: in function <.../ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceHook/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11641: in function `BlizzardAPIHook'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:3163: in function <Interface/AddOns/ArkInventory/Core/ArkInventory.lua:3129>
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>
Locals: (*temporary) = <function> defined =[C]:-1

Upon mouseover on any inventory item that does not exist (i.e. was just auctioned) throws the following:

Message: ...ace/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua:563: attempt to index field 'ARKTTD' (a nil value)
Time: Tue Oct 10 12:55:23 2023
Count: 43
Stack: ...ace/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua:563: attempt to index field 'ARKTTD' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Core/ArkInventoryTooltip.lua"]:563: in function `TooltipSet'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:8851: in function `Frame_Item_OnEnter'
[string "*ArkInventory.xml:484_OnEnter"]:1: in function <[string "*ArkInventory.xml:484_OnEnter"]:1>

Locals: (*temporary) = true
(*temporary) = <function> defined =[C]:-1

This is live Wrath client with 0 additional addons loaded.

**Comment by wendybird** [comment] 2023-10-10 18:38
Same errors for me on current wrath client. Using Bagnon as a bandaid solution, but man.. it's just not the same. T_T

**Comment by arkayenro** [comment] 2023-10-10 20:57
[3.10.17-alpha-1](https://legacy.curseforge.com/wow/addons/ark-inventory/files/4761101),  currently has the fix for this issue -

**Comment by arkayenro** [comment] 2023-10-10 20:59
duplicate of #1822

**Closed** 2023-11-05 10:29 UTC
