### ISSUE TITLE
addon failure at start of wow

### ISSUE THREAD

**Issue by damianjyates** [arkayenro/arkinventory#1145] opened 2019-03-12 19:33 UTC
Date: 2019-03-12 12:28:01
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ArkInventory\ArkInventory.lua line 865:
   attempt to index global 'WorldMapTooltip' (a nil value)
Debug:
   ArkInventory\ArkInventory.lua:865: in main chunk
Locals:
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:74
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 ARL_DatamineCopyFrame = ARL_DatamineCopyFrame {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 740
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 398
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 BOOKTYPE_PROFESSION = "professions"
 AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropdownButtonHighlightTexture {
 }
 VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture = VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture {
 }
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @Interface\FrameXML\UnitFrame.lua:794
 PaperDollTitlesPaneButton10BgTop = PaperDollTitlesPaneButton10BgTop {
 }
 ERR_NOAMMO_S = "%s"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2372
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 950
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight {
 }
 LFGTeleport = <function> defined =[C]:-1
 LE_GAME_ERR_ONLY_ONE_QUIVER = 32
 SpellButton6Cooldown = SpellButton6Cooldown {
 }
 SLASH_LibQTip1 = "/qtip"
 ToggleEncounterJournal = <function> defined @Interface\FrameXML\UIParent.lua:910
 LOSS_OF_CONTROL_DISPLAY_FEAR = "Feared"
 Graphics_QualityText = Graphics_QualityText {
 }
 TalentMicroButtonAlertShadowTopLeft = TalentMicroButtonAlertShadowTopLeft {
 }
 OverrideActionBarButton6Shine11 = OverrideActionBarButton6Shine11 {
 }
 ROGUE_COMBAT_CORE_ABILITY_4 = "Melee attack that spends Combo Points."
 JoinSkirmish = <function> defined =[C]:-1
 Advanced_GraphicsAPIDropDownButtonHighlightTexture = Advanced_GraphicsAPIDropDownButtonHighlightTexture {
 }
 MultiBarRightButton7Shine9 = MultiBarRightButton7Shine9 {
 }
 BankFrameItem17SearchOverlay = BankFrameItem17SearchOverlay {
 }
 LFGListSearchPanelScrollFrameButton10BottomRight = LFGListSearchPanelScrollFrameButton10BottomRight {
 }
 DMG_LCD = "DMG"
 RaidGraphics_EnvironmentalDetailSlider = RaidGraphics_EnvironmentalDetailSlider {
 }
 Is64BitClient = <function> defined =[C]:-1
 SecureCmdItemParse = <function> defined @Interface\FrameXML\ChatFrame.lua:1145
 SLASH_STOPATTACK1 = "/stopattack"
 MultiCastActionB
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AckisRecipeList, v8.1.1
  Altoholic, vr190
  ArcHUD3, vv5.0.3
  ArkInventory, v30821
  Carbonite, vv8.1.2.1
  DataStore, vr65
  DataStoreCharacters, vr43
  TomTom, vv80001-1.0.2
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=107)

Any idea why this is happening?

**Comment by ellotheth** [comment] 2019-03-12 19:49
Dupe of #1144

**Comment by jeffv2011** [comment] 2019-03-12 20:57
Same. Bags will not open nor can I even access the addon via the AddOn Blizz menu.

**Comment by Ibglitrbug** [comment] 2019-03-13 00:41
Same . is someone working on this that is all i would like to know if so thats great and i will await the new up date.?

**Comment by Koviko** [comment] 2019-03-13 05:49
[Fixed.](https://github.com/arkayenro/arkinventory/issues/1144#issuecomment-472284697) You'll have to manually patch the addon, for now.

**Comment by arkayenro** [comment] 2019-03-21 05:35
please upgrade to 3.08.23

**Closed by arkayenro** 2019-03-21 05:35 UTC
