### ISSUE TITLE
Toy box issues.

### ISSUE THREAD

**Issue by tomaj84** [arkayenro/arkinventory#852] opened 2016-09-07 01:34 UTC
A few current things screwing with my ability to use the toy box.

1. I can't actually use my regular toy box page correctly. [As you can see](http://i.imgur.com/7ohTSQQ.jpg), I have quite a few more than 11 toys, but it isn't showing anything but these. Prior to updating, I was able to open and close the toy box a few times in order to get it working correctly, now, no such luck.

2. I can't see which items are on cooldown. [Here](http://i.imgur.com/pc1icjw.jpg), my Coin of Many Faces still has well over 4 hours left on cooldown, but it remains looking like it can be used.

3. This leads me to my final issue. When in ArkInventory's version of the Toy Box, I can't actually USE anything. Clicking on an item doesn't do anything. To that end, it also considers every single item in my toy box "unusable" as well (if you enable the tinting for unusable items).

**Comment by nitz** [comment] 2016-09-08 19:31
As for your first issue: Have you updated recently? I had that same problem, but his recent patch had a note: `* fixed - issue with toybox source filter`, which solved that issue for me. (Before then, I'd have to manually go into sources and 'Check All')

I'm still experiencing an issue similar to your third issue, though: Often when trying to use an item from the toybox, I get the blizzard UI taint error saying that an addon was calling a protected function (or something of that nature), giving me the option to disable the addon or to ignore it. (I'll snag a screenshot of the message the next time it shows up.)

**Comment by tomaj84** [comment] 2016-09-08 22:21
Yes, I updated and still had the issue with not all my toys showing up in the default toy box.

For the other, I don't even get that far, I just can't interact with anything actually in the AI toy box.

**Comment by arkayenro** [comment] 2016-09-08 22:44
> I can't actually use my regular toy box page correctly. As you can see, I have quite a few more than 11 toys, but it isn't showing anything but these.

what are the filter settings like?  specifically the source ones (there is a weird base ui thing where the source filters disappear when you turn them off) so try clicking on the select all and see if it happens again after that (just that the source filter seems to be saved across sessions so if you logged out when they were all off then thats how they will stay until you fix them manually)

**Comment by arkayenro** [comment] 2016-09-08 22:45
> I can't see which items are on cooldown. Here, my Coin of Many Faces still has well over 4 hours left on cooldown, but it remains looking like it can be used.

i'll look into this, i never really noticed

**Comment by arkayenro** [comment] 2016-09-08 22:46
> When in ArkInventory's version of the Toy Box, I can't actually USE anything. Clicking on an item doesn't do anything

which is normal, toys are secure, i cant call them without tripping an invalid action warning.  all you can do from the ai window is drag them to an actionbar button

> To that end, it also considers every single item in my toy box "unusable" as well (if you enable the tinting for unusable items).

will look into that as well

**Comment by nitz** [comment] 2016-09-08 22:52
> which is normal, toys are secure, i cant call them without tripping an invalid action warning. all you can do from the ai window is drag them to an actionbar button

I actually get the taint error when using the original toybox too. I can't seem to reproduce it at the moment, but next time I do, I'll try to snag a video of it.

The only call stack I have is from a previous session, and I couldn't make much of it:

```
2x [ADDON_ACTION_FORBIDDEN] AddOn 'ArkInventory' tried to call the protected function 'UseToy()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `UseToy'
...faceBlizzard_Collections\Blizzard_ToyBox.lua:144: in function `ToySpellButton_OnClick'
[string "*:OnClick"]:4: in function <[string "*:OnClick"]:1>

Locals:
nil
```

**Comment by nitz** [comment] 2016-09-08 22:53
>what are the filter settings like? specifically the source ones (there is a weird base ui thing where the source filters disappear when you turn them off) so try clicking on the select all and see if it happens again after that (just that the source filter seems to be saved across sessions so if you logged out when they were all off then thats how they will stay until you fix them manually)

Since your last patch, I've not had any issues with the filters unselecting. (And not needed to reselect 'check all' to see all my toys.) I'll keep an eye out to see if they change (or if changing them effects the taint issue.)

**Comment by arkayenro** [comment] 2016-09-08 22:59
the tint issue will be in the next release (it was seeing the "already known" red text)

the previous taint was from me leaving in the UseToy command, which i commented out recently to stop that

**Comment by arkayenro** [comment] 2016-09-08 23:12
colldown should be fixed in the next release as well - needs a refresh to display though (have to work out how to get it to happen automatically)

**Comment by tomaj84** [comment] 2016-09-09 08:06
> what are the filter settings like? specifically the source ones (there is a weird base ui thing where the source filters disappear when you turn them off) so try clicking on the select all and see if it happens again after that (just that the source filter seems to be saved across sessions so if you logged out when they were all off then thats how they will stay until you fix them manually)

Truthfully, I'm not even sure how to check on the source settings.

The only filter I'm using is a custom filter where I've manually added all my favorite items in the toy box to a separate category. Unless I'm misunderstanding what you're asking here?

**Comment by tomaj84** [comment] 2016-09-10 00:03
Also, for what it's worth the tint thing also goes for heirlooms in your bags.

**Comment by arkayenro** [comment] 2016-09-11 04:56
same fix will fix both of them

**Comment by arkayenro** [comment] 2016-09-11 04:57
fixed in 30707

**Closed by arkayenro** 2016-09-11 04:57 UTC
Labels: bug
