### ISSUE TITLE
[BUG] All ToyBox Filters unchecked when Monitoring ToyBox

### ISSUE THREAD

**Issue by fubaWoW** [arkayenro/arkinventory#1702] opened 2022-11-28 01:36 UTC
**What version number you are using?**
3.10.09-alpha-2

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail

**What language is the game client set to?**
English

**Describe the bug**
Open ToyBox always have all Filters set to "unchecked" on open the Original ToyBox Page.

**Screenshots**
![image](https://user-images.githubusercontent.com/41425685/204173492-c1731f78-b320-4563-bdeb-fd6bae51c894.png)
![image](https://user-images.githubusercontent.com/41425685/204173504-cdc99acc-a37c-47dc-b6a3-57b904094b7f.png)

**Comment by arkayenro** [comment] 2022-11-28 03:13
should be fixed next release. looks like they got inverted at some point.

**Comment by arkayenro** [comment] 2022-11-28 03:15
duplicate of #1575

**Comment by arkayenro** [comment] 2022-11-28 04:23
fixed, hopefully, in 3.10.09 alpha 3

**Comment by fubaWoW** [comment] 2022-11-28 13:34
thanks, will test it later :)

**Closed** 2022-11-28 20:36 UTC
Labels: bug
