### ISSUE TITLE
aborting a bank restack

### ISSUE THREAD

**Issue by wownob** [arkayenro/arkinventory#737] opened 2015-11-29 22:57 UTC
After the latest patch (3.05.12) a bank restack (including storing reagents) always leads to "restacking bank aborted".

**Comment by pervel** [comment] 2015-12-01 10:29
I can confirm this. It appears to happen when you haven't yet purchased all available bank slots.

**Comment by wownob** [comment] 2015-12-04 09:18
pervel is right.
I tested the restack with a char which has all bank slots available.
Restack runs ok.
If I withdraw one bag form a bankslot, the error Comes up again.

**Comment by arkayenro** [comment] 2016-07-03 11:37
yes, issue is due to unpurchased bank slots

fixed in 3.06.00

**Closed by arkayenro** 2016-07-03 11:37 UTC
