### ISSUE TITLE
[BUG] Rule "outfit ()" does not work in Wrath Classic

### ISSUE THREAD

**Issue by lossolsun** [arkayenro/arkinventory#1606] opened 2022-10-02 01:44 UTC
**What version number you are using?**
3.09.68

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Wrath Classic

**What language is the game client set to?**
English

**Describe the bug**
The "outfit ()" rule does not work in Wrath Classic. It works in retail on the same version of the addon. Having the rule enabled and assigned to a bar does not cause any items to move to that bar.

**To Reproduce**
Create an outfit rule, assign it to a bar, and nothing happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/71242459/193434221-05beee1b-4078-4dd8-adb6-6a6fb7180387.png)
![image](https://user-images.githubusercontent.com/71242459/193434258-6f77dc22-ca1a-4327-857c-fe7554dbbfb0.png)
![image](https://user-images.githubusercontent.com/71242459/193434267-e6fedbde-c85c-439a-b445-8d01ed482528.png)
![image](https://user-images.githubusercontent.com/71242459/193434307-976c9365-db39-49eb-8203-432fe9a6d7c5.png)

**Additional context**

**Comment by arkayenro** [comment] 2022-10-02 04:41
duplicate of #1593

**Comment by arkayenro** [comment] 2022-10-02 09:23
fixed in 3.10.00 alpha 6

**Closed by arkayenro** 2022-10-02 09:23 UTC
