### ISSUE TITLE
[BUG] Choppy Gameplay & Random Disappearance of User Interface in Dragonflight Beta

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1618] opened 2022-10-17 03:01 UTC
**What version number you are using?**
v31000.DragonFlight.Alpha.11

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Dragonflight Beta

**What language is the game client set to?**
English

**Describe the bug**
With ArkInventory (+Configuration, Rules, Search) enabled, I notice periodic hiccups during gameplay like when the frame rate is choppy.  It doesn't prevent me from doing anything, it's just like the game is lagging.

Also, periodically the user interface elements will just disappear like when you hit Alt-Z to toggle the user interface for screen captures.  If I /reload, then it comes back.  There's no rhyme or reason as to when it happens so it's impossible to *make* it happen.  Some times it happens when I'm just sitting in town, others times when I'm flying, and the worst is when I'm in the middle of combat and it disappears.

**To Reproduce**
The choppy gameplay is pretty much consistent.

The disappearing user interface happens randomly so it's unlikely that you'll be able to force it to happen.

**Screenshots**
As I said, it's exactly like hitting Alt-Z.  The user interface just vanishes and I can still move around and play.  It's just I can't see any of the UI elements.

![WoWScrnShot_101622_225844](https://user-images.githubusercontent.com/13042214/196079919-716a200d-1e6e-4981-b448-500172fe87ab.jpg)

**Additional context**
I've had to disable ArkInventory for now while I do other beta-testing as it causes some real problems (especially while in combat).

I hope that reporting this sort of stuff helps prepare this awesome addon for Dragonflight.  I know you're likely swamped with trying to fix issues with the Wrath classic launch, too.

**Comment by arkayenro** [comment] 2022-10-17 05:14
try alpha 13 - im not sure if its something from arkinventory or just beta stuff in general (especially the extra action bars) but i havent had that issue for a while now.

**Comment by Calesta** [comment] 2022-10-19 03:18
I tried Alpha 13 and got lots of warnings at startup that just kept repeating over and over.

![WoWScrnShot_101822_225857](https://user-images.githubusercontent.com/13042214/196589440-8b59ddcd-b9e4-44a1-be69-180967a6eeb7.jpg)

I turned off the zero size bag alert for now.

The choppiness still seems to be there.  If I walk a straight line, then it seems like there's a regular cadence to it. 

I didn't experience the disappearing UI behavior, though.

If you need any more detail, then please let me know.  Thanks!

**Comment by arkayenro** [comment] 2022-10-19 08:55
try alpha 14

**Comment by tflo** [comment] 2022-10-19 16:46
I'm having the same issue, but on 9.2.7 and only since today. _If_ it is related to ArkInventory, then it very likely has started with alpha 14 for me, because I literally never had my UI disappearing before. (I say "very likely" bc the UI disappearing seems to be random, and it might be possible – though unlikely – that it just didn't happen the last days due to randomness.)

Is it safe (in terms of SV data) to go back a few alphas, or even back to the latest non-alpha (3.09.68)?

**Comment by masterkain** [comment] 2022-10-19 23:21
I have the same issue, started today in Classic Wrath, fps drops due to Arkinventory, I have 4/5 custom rules, I recall alpha 11 was fine

**Comment by masterkain** [comment] 2022-10-19 23:25
just rested 11 and I can confirm I don't have fps drops compared to 14, also opening the bag is instant whereas in 14 you can visually see a reshuffle each opening

**Comment by arkayenro** [comment] 2022-10-19 23:37
@tflo your UI in retail is disappearing?

**Comment by arkayenro** [comment] 2022-10-19 23:40
@masterkain what is your window sorting set to?  manual, on open, instant?

**Comment by masterkain** [comment] 2022-10-20 00:38
> @masterkain what is your window sorting set to? manual, on open, instant?

I left the default this time, on window open

**Comment by masterkain** [comment] 2022-10-20 00:39
however it's weird -- I just noticed that curse background updated again to 14 after downgrading and I don't have issue at this time, maybe the problem was with 13 and I did not notice

**Comment by tflo** [comment] 2022-10-20 00:42
> @tflo your UI in retail is disappearing?

Yes, in 9.2.7. When it disappears I can only get it back with /reload, except once, where it came back by itself for 2 seconds but then disappeared again. Usually this is preceded by a hefty FPS drop.

Weirdly, in the last few hours the issue was not there. Maybe interfering with something else, but I don't know what. It happens/happened on all toons I played today (8 or so; "played" = doing more than just the mission table).

**Comment by masterkain** [comment] 2022-10-20 01:49
issue started again in 14, it's probably manifesting itself over time

**Comment by tflo** [comment] 2022-10-20 22:55
Still happening today (UI disappearance). The reason that it stopped happing as often as before might be that I reduced my max FPS from 60 to 45 at some point, maybe, no idea.

Typical situations: My AH toon pulling from an (over)full mailbox; other toons opening the bank (with both bank and bags well filled).

**Comment by tflo** [comment] 2022-10-21 02:20
Went back to 3.09.68.

Symptoms are gone (massive FPS drop, UI disappearing), no database or rules/categories issues from going back exposed – so far.

I know, not much help for you. But at least I'm pretty sure now that it was indeed bc of one of the alphas (which I wasn't sur about before ;)

**Comment by nate302** [comment] 2022-10-21 04:06
I can confirm this. Reverted back and choppiness went away. I was getting choppiness any time my hunter would even autoshot on dummies.

**Comment by tflo** [comment] 2022-10-21 16:53
Quoting myself…
> no database or rules/categories issues from going back exposed – so far

Well, it seems I have lost some database entries (items), but not yet sure what exactly. (SV file has shrinked by 0.4MB compared to my last alpha-14 copy, but still in "normal" range (9MB).)

**Comment by arkayenro** [comment] 2022-10-22 04:50
can you try alpha 15.  log into the game, open the config, and enable debug mode.

let me know if anything keeps running when it shouldnt.

**Comment by nate302** [comment] 2022-10-22 06:35
![image](https://user-images.githubusercontent.com/1392429/197324281-3204eede-6c0a-4b74-9f89-fa588e7f5864.png)

Lag starts a minute or two after hitting the dummies.

**Comment by nate302** [comment] 2022-10-22 06:41
Message: ...ace\AddOns\ArkInventory\Core\ArkInventoryStorage.lua:1617: code failure: blizard_id is nil
Time: Fri Oct 21 23:40:59 2022
Count: 1048
Stack: ...ace\AddOns\ArkInventory\Core\ArkInventoryStorage.lua:1617: code failure: blizard_id is nil
[string "=(tail call)"]: ?
[string "=[C]"]: in function `assert'
[string "@Interface\AddOns\ArkInventory\Core\ArkInventoryStorage.lua"]:1617: in function `BlizzardBagIdToInternalId'
[string "@Interface\AddOns\ArkInventory\Core\ArkInventoryStorage.lua"]:1490: in function `?'
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:114: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:24: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:20>
[string "@Interface\AddOns\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <Interface\AddOns\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by arkayenro** [comment] 2022-10-22 10:28
what items in the 4th bag have a cooldown?

**Comment by nate302** [comment] 2022-10-22 18:24
Wouldn't bag 4 be my quiver?

![image](https://user-images.githubusercontent.com/1392429/197356818-cff54125-e4fd-4967-8b20-ed0106d11ca4.png)

**Comment by nate302** [comment] 2022-10-22 18:27
![image](https://user-images.githubusercontent.com/1392429/197356961-001ebe8f-6088-42ba-8301-5c151a54801a.png)

**Comment by nate302** [comment] 2022-10-22 18:29
![image](https://user-images.githubusercontent.com/1392429/197357048-cba5fa7e-1ead-4c84-aba3-fae51b06c65a.png)

**Comment by arkayenro** [comment] 2022-10-22 22:45
yes, bag 4 is your quiver - so youre using classic or wrath, not retail or dragon flight.

hunter ammo is using a bag item each time you shoot so it has to scan - this is perfectly normal.

if this is an issue it should lag every time you shoot, not 1-2 minutes later, immediately.

what is output when the lag starts?

**Comment by nate302** [comment] 2022-10-22 22:54
For me the lag is almost instantaneous and it gets worse as time goes on. Even with just autoshooting a dummy. The log output I put is from when I start autoshooting the dummies and the lag only gets worse. For now I have the addon disabled and I have no lag at all.

**Comment by Calesta** [comment] 2022-10-22 23:08
I tried Alpha 16 and am happy to report that the stuttering I was seeing seems to be gone (or at least not noticeable) and I haven't seen the UI disappear at all.  Progress!

**Comment by arkayenro** [comment] 2022-10-22 23:49
@nate302  about the only thing i can think of doing for hunters is to add an extra check to see if you are in combat and the bag type is a quiver or ammo pouch and then abort until youre out of combat.

no other class is impacted because none of them use items for ammo.

**Comment by nate302** [comment] 2022-10-22 23:53
Yeah that makes sense. For now I had to disable it.

**Comment by arkayenro** [comment] 2022-10-23 02:50
@Calesta is your character a hunter?  

@nate302 try alpha 17, it should now wait until you exit combat to scan projectile bags

**Comment by Calesta** [comment] 2022-10-23 03:35
@arkayenro Calesta is a mage.

**Comment by nate302** [comment] 2022-10-23 04:23
> @Calesta is your character a hunter?
> 
> @nate302 try alpha 17, it should now wait until you exit combat to scan projectile bags

Put debug on, I can see the ignored: in combat entries, and lag appears to be gone!

**Comment by sariouso** [comment] 2022-10-24 17:40
> 

I'm still having this issue as a hunter on WotLK Classic. I'm guessing it's because I use a normal bag for my arrows. Anyway to fix it? I would just use alpha 11, but the items from some quests cause errors and stops arkinventory from even loading.

**Comment by nate302** [comment] 2022-10-24 17:55
I did also notice the same lag on my bank alt when receiving mail or putting items into the bank, and also while changing forms on my Druid. At least hunter combat works with arrows in the quiver.

**Comment by sariouso** [comment] 2022-10-24 17:57
> I did also notice the same lag on my bank alt when receiving mail or putting items into the bank, and also while changing forms on my Druid. At least hunter combat works with arrows in the quiver.

I've had that issue with mail for years.

**Comment by nate302** [comment] 2022-10-24 19:39
This is different. It’s not a lag spike, but it gets to the point where receiving mailed items means disabling the add on or fps is just unbearable.

**Comment by sariouso** [comment] 2022-10-24 20:15
> 

Gotcha. I don't think I'm having that issue.

**Comment by Calesta** [comment] 2022-10-26 21:31
Not sure if the others have had their related issues addressed, but I would say this issue was resolved given my initial report.  I'm sure you want to start cleaning up some of these lagging issues so you can focus on the issue related to the Retail client now.

**Comment by sariouso** [comment] 2022-10-27 00:03
> Not sure if the others have had their related issues addressed, but I would say this issue was resolved given my initial report. I'm sure you want to start cleaning up some of these lagging issues so you can focus on the issue related to the Retail client now.

Still unusable past Alpha 11 for me.

**Comment by arkayenro** [comment] 2022-10-27 01:55
@sariouso so alpha 11 works ok for you?  no lag anywhere with it?

**Comment by arkayenro** [comment] 2022-11-06 12:09
should have been fixed in 3.10.03, is anyone still having this issue?

**Closed** 2022-11-17 00:23 UTC
