### ISSUE TITLE
[BUG] Map and other windows no longer respond to ESC key in combat

### ISSUE THREAD

**Issue by Martypedia** [arkayenro/arkinventory#1673] opened 2022-11-18 16:09 UTC
**What version number you are using?**
3.10.05

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Retail (live)

**What language is the game client set to?**
English

**Describe the bug**
The map as well as other in-game windows can no longer be closed with the ESC key in combat while ArkInventory is running (producing "Interfact action falied because of an AddOn). Respective hotkeys (like M for the map) still close them.

**To Reproduce**
Open map, enter combat, try to close map with ESC while in combat.

**Comment by arkayenro** [comment] 2022-11-18 23:23
i can reproduce it, and i know where its coming from, but theres no way for me to work around it at the moment,

**Comment by arkayenro** [comment] 2022-11-19 04:08
found the cause, will be fixed in the next release/alpha

**Comment by Martypedia** [comment] 2022-11-19 04:37
Awesome! Been using AI since Cata and it's become a staple I recommend to literally anyone I meet. Could you briefly elaborate what was happening?

**Comment by arkayenro** [comment] 2022-11-19 07:27
blizzard made something secure when in combat that didnt used to be, that is closing ui panels.

i dont close ui panels but i did take control closing the bags.  the issue was that the code when you press escape closes the bags *and* the uipanels, and because ther bag closes were no no blizzard (secure) code, it was failing when in combat.

i checked my code and it looked like id already moved everything out of there to somewhere else but left in some debug stuff probably just in case i ran into an issue.

to fix it i basically stopped replacing the bag close code so it remains blizzard secure code and no longer fails.

**Comment by arkayenro** [comment] 2022-11-19 08:41
fixed in 3.10.06

**Closed by arkayenro** 2022-11-19 08:41 UTC
Labels: bug
