### ISSUE TITLE
[BUG] HookOpenAllBags:GearManagerDialogPopup not found error

### ISSUE THREAD

**Issue by Cabro** [arkayenro/arkinventory#1815] opened 2023-08-26 19:28 UTC
![image](https://github.com/arkayenro/arkinventory/assets/1155017/0f398c8b-391f-4899-a0c0-9d5d15c78eb0)

Just opened mailbox and grabbed some AH mails.

Wotlk 
v 31016

**Comment by arkayenro** [comment] 2023-08-26 23:51
duplicate of #1801 

fixed in 31016-alpha-1

**Closed by arkayenro** 2023-08-26 23:51 UTC
