### ISSUE TITLE
[BUG] Performance degredation during extended play sessions

### ISSUE THREAD

**Issue by Rychard** [arkayenro/arkinventory#1637] opened 2022-10-27 18:30 UTC
**What version number you are using?**

`v31002`

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**

WotLK Classic

**What language is the game client set to?**

EN-US

**Describe the bug**

 There seems to be some performance issues with the latest update (at least, in WOTLK Classic).

Initially, everything is fine, but progressively slows down as your inventory is modified, eventually bringing the game to a slideshow for multiple seconds when looting mobs, receiving quest rewards, or really anything that alters the contents of your bags.  In fact, even opening my bags will tank performance for a few seconds.  Performance returns to normal a few seconds after any of these events occur, but closing and reopening the bags again will reproduce the slowdown.  Doing a `/reload` will also restore performance temporarily, though this is merely a temporary fix.

Disabling the addon brings performance back to normal.

**To Reproduce**

Play the game for a period of time, killing and looting mobs.  It seems to be correlated to the number of times you've looted items, so I am unsure if the *duration* of the session actually has any impact at all.

I ran `/arkinventory debug`, and spoke to a (repair) vendor (automatic junk selling and repairing is being handled by [Leatrix Plus](https://www.curseforge.com/wow/addons/leatrix-plus-wrath)).  Since it's written to the chat window, my chat addon ([Prat](https://www.curseforge.com/wow/addons/prat-3-0)) adds timestamps to each line.  As you can see, the entire process takes place over multiple seconds, and during this time, the framerate drops to single-digit values.  Previously, this was a nearly instantaneous operation.

```text
[14:13:03] ArkInventory: DEBUG> EVENT: GUILDBANK_UPDATE_MONEY
[14:13:04] ArkInventory: DEBUG> set draw status for 1 to [2] (SET)
[14:13:04] Repaired for 5 Silver, 92 Copper.
[14:13:04] ArkInventory: DEBUG> EVENT: MERCHANT_ENTER - MERCHANT_SHOW
[14:13:04] ArkInventory: DEBUG> CalculateBars( ARKINV_Frame1ScrollContainer ) for [Elluria] start
[14:13:04] ArkInventory: DEBUG> CalculateBars( ARKINV_Frame1ScrollContainer ) end: 9ms
[14:13:04] ArkInventory: DEBUG> CalculateContainer( ARKINV_Frame1ScrollContainer ) start
[14:13:04] ArkInventory: DEBUG> CalculateContainer( ARKINV_Frame1ScrollContainer ) end: 0ms
[14:13:04] ArkInventory: DEBUG> EVENT: GUILDBANK_UPDATE_MONEY
[14:13:04] ArkInventory: DEBUG> EVENT: ITEM_LOCK_CHANGED, 0, 12
[14:13:04] ArkInventory: DEBUG> EVENT: ITEM_LOCK_CHANGED, 1, 12
[14:13:04] Sold junk for 42 Silver, 86 Copper.
[14:13:05] ArkInventory: DEBUG> EVENT: BAG_UPDATE, { [1]=1, [-2]=1, [0]=1 }
[14:13:05] ArkInventory: DEBUG> ScanBag( 1 )
[14:13:05] ArkInventory: DEBUG> ScanBag( 0 )
[14:13:05] ArkInventory: DEBUG> EVENT: { [PLAYER_MONEY]=1 }
[14:13:06] ArkInventory: DEBUG> EVENT: LOCATION_SCANNED, { [1]=1 }
[14:13:07] ArkInventory: DEBUG> EVENT: CHANGER_UPDATE, { [1]=1 }
[14:13:07] ArkInventory: DEBUG> EVENT: LOCATION_DRAW, { [1]=1 }
[14:13:08] ArkInventory: DEBUG> EVENT: LOCATION_SCANNED, { [1]=1 }
[14:13:08] ArkInventory: DEBUG> EVENT: CHANGER_UPDATE, { [1]=1 }
[14:13:08] ArkInventory: DEBUG> EVENT: LOCATION_DRAW, { [1]=1 }
[14:13:08] ArkInventory: DEBUG> CalculateBars( ARKINV_Frame1ScrollContainer ) for [Elluria] start
[14:13:08] ArkInventory: DEBUG> CalculateBars( ARKINV_Frame1ScrollContainer ) end: 9ms
[14:13:08] ArkInventory: DEBUG> CalculateContainer( ARKINV_Frame1ScrollContainer ) start
[14:13:08] ArkInventory: DEBUG> CalculateContainer( ARKINV_Frame1ScrollContainer ) end: 0ms
[14:13:09] ArkInventory: DEBUG> EVENT: LOCATION_SCANNED, { [2]=1 }
[14:13:09] ArkInventory: DEBUG> EVENT: LOCATION_DRAW, { [2]=1 }
```

**Comment by Werwolfsoul** [comment] 2022-10-27 22:13
I have the same issues. I am using the same version but (not 100% sure) it also reproduced in previous version v31001.
I'll try to install an earlier version tomorrow to see if the issues will reproduce with it or not.

**Comment by arkayenro** [comment] 2022-10-27 22:44
duplicate of #1624

**Comment by Stoytovisiao** [comment] 2022-10-28 09:03
What version number you are using?

**v31002**

What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta

**WotLK Classic**

What language is the game client set to?

**ES-ES**

I have the same problems as user Rychard.
I don't use Prat.

**Comment by arkayenro** [comment] 2022-10-28 09:07
the normal debug isnt granular enough, you ll need to enable thread debug in config > advanced > threads

**Comment by Mattyd221** [comment] 2022-10-28 14:43
I am having this same issue as well in wrath classic. I reverted back to 3.09.68 and the issue went away.

**Comment by sirspamalotz** [comment] 2022-10-28 21:06
having the same issue also

**Comment by byWulf** [comment] 2022-10-28 21:10
I also notice the performance degration since the last update. If you need any help at debugging or more information please write!

**Comment by panoulil** [comment] 2022-10-29 06:34
Performance has cratered for me since the most recent update in WOTLK. I'm a hunter so not sure if arrows leaving inventory make it worse. Typically run at 100 FPS with vsync and everything enabled. 5 mans even were causing FPS to be less than 15. Running on a 3080 and i7-12700k.
Can give logs or whatever to assist if needed.

**Comment by arkayenro** [comment] 2022-10-29 07:13
try 3.10.02 alpha 2

**Comment by byWulf** [comment] 2022-10-29 13:38
@arkayenro Confirmed, after few hours and many looting, 3.10.02 alpha 2 does not have performance problems :)

**Closed** 2022-10-30 00:37 UTC
