### ISSUE TITLE
[BUG] Outfit rule is not parsing in-game wotlk equipment manager

### ISSUE THREAD

**Issue by aamurao** [arkayenro/arkinventory#1617] opened 2022-10-16 02:57 UTC
**What version number you are using?**
v3.09.68 [WotLK]

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
WotLK Classic

**What language is the game client set to?**
English

**Describe the bug**
This rule - outfit( "ret" ) - is not working at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/65829156/196015807-169ea0e1-b7e2-44ad-9064-bd7df662dbcb.png)
![image](https://user-images.githubusercontent.com/65829156/196015833-850d3f74-f433-4362-b674-4328f1b2c7ed.png)

**Comment by btronn** [comment] 2022-10-16 03:39
Me too

**Comment by arkayenro** [comment] 2022-10-16 03:55
duplicate of #1593 

fixed in 3.10.00 alpha 6

**Closed by arkayenro** 2022-10-16 03:55 UTC
