### ISSUE TITLE
Reagent Bank: Restack Doesn't Work / Item is Locked

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#1460] opened 2021-06-10 22:19 UTC
I'm using the latest version 3.09.50 and 'Restack' doesn't seem to work correctly in my bank's reagent bank container. When I click on it, I see the message 'Item is Locked' but not always. It seems like the process gets 'stuck' - sorry for the non-technical term - and doesn't fully complete.  I had a similar issue a LONG, LONG time ago, but you found the issue and fixed it and it's worked ever since.

I noticed it a while back - although I can't remember which version it started - but I just got around to actually typing up an issue. Hopefully, you'll have some time to check it out. As always, thanks for the amazing addon!

**Comment by arkayenro** [comment] 2021-06-11 00:46
is restack set to restack (ai code) or cleanup (blizzard code)?

**Comment by Calesta** [comment] 2021-06-11 02:44
Blizzard: Cleanup

**Comment by arkayenro** [comment] 2021-06-11 03:21
the first time around i added a hardcoded 0.2 second delay so it must not be enough in some circumstances.

i've added a config value to let you adjust that delay to something that will work for you.

you basically just keep increasing it until the error stops.

will be in the next alpha/release

**Comment by Calesta** [comment] 2021-06-23 18:44
I updated to the latest version and tried various delay values and even at the maximum 5 second delay, I'm still getting the 'item is locked' message and some reagents aren't restacked.  It appears to be isolated to the reagent bank so it's not a critical issue.  It's just one of those little things that I've gotten used to doing to make sure I'm optimizing my storage space and having to do some of it manually is a bummer.

If there's anything else I can provide to maybe help isolate the issue, then please let me know.  I'd imagine that I'm not the only one with this problem so it might be helpful.  Would moving everything out of the reagent bank, run refresh/restack, and then put everything else back in the reagent bank help with whatever is causing the item lock?

Thanks again for the quick response to issues.  It's very much appreciated.

**Comment by arkayenro** [comment] 2021-06-24 00:50
i never seem to run into it unless i dont have a delay but ill keep looking to see if i can find a way to make it work

in the mean time is there any reason you cant use the arkinventory restack instead of the blizzard cleanup?

**Comment by arkayenro** [comment] 2021-06-24 00:52
if possible, maybe install bugrabber and bugsack, see if they capture the error.  my code is threaded which tends to screw up error traces but you never know, it might get something useful

**Comment by Calesta** [comment] 2021-06-26 20:18
I swapped to the ArkInventory: Restack option and didn't experience the issue.  Honestly, I don't recall which was the default and/or why exactly I switched to the Blizzard: Cleanup option if I did.  I'll just keep using the Restack code option.

I'll let you close this issue if you want as I have a working alternative.  Thanks again for the time/effort!

**Comment by arkayenro** [comment] 2021-06-27 01:54
blizzards cleanup is much faster as the servers do the actual work.  the issue is that theres no way to tell when it has finished, thus the guess of 0.2 seconds before the rest of the code keeps running.

my code is slower but as i always have control over it it knows how to wait

**Closed by arkayenro** 2021-06-27 01:54 UTC
Labels: bug
