### ISSUE TITLE
[BUG] WOTLK bags are just broken

### ISSUE THREAD

**Issue by sidamakid** [arkayenro/arkinventory#1592] opened 2022-09-02 23:38 UTC
**What version number you are using?**
Interface: 30400
Addon Version 3.0.9

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
WOTLK Classic

**What language is the game client set to?**
English

**Describe the bug**
Everything just is broken.

**To Reproduce**
Steps to reproduce the behaviour, if possible:
Check the ArkInventory.lua file and change the addon loaded file maybe.

**Screenshots**
![image](https://user-images.githubusercontent.com/38231721/188246629-fbc1dd7e-3d3f-4a68-a3e1-1783d0fc2418.png)

**Additional context**

**Comment by aamurao** [comment] 2022-09-03 00:33
![image](https://user-images.githubusercontent.com/65829156/188248901-d8456dd0-b803-441c-aa55-4be161901428.png)

**Comment by Nitti2909** [comment] 2022-09-03 05:49
Same error here...

**Comment by arkayenro** [comment] 2022-09-03 06:34
Duplicate of #1591

**Closed by arkayenro** 2022-09-03 06:34 UTC
Labels: blizzard, wrath
