### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Kdcargill** [arkayenro/arkinventory#1593] opened 2022-09-15 16:58 UTC
**What version number you are using?**
v3.09.68(Wrath of the Lich King)

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Wrath of the Lich King Classic Live

**What language is the game client set to?**
English

**Describe the bug**
Outfit rules do not appear to be working. After creating the rule specifically from the list of example rules and assigning it to a Bar within ArkInventory, nothing happens. I do not use any other equipment manager addons other than the default one included in the game.

**To Reproduce**
Created a rule with the formula:
outfit()
Hit accept
Assign rule to a Bar and make sure rule is set to active.

**Screenshots**
![image](https://user-images.githubusercontent.com/54863991/190463145-8a378870-ef7c-4d74-8a8b-4443f1570e76.png)
![image](https://user-images.githubusercontent.com/54863991/190463414-9fc6929c-24a3-46e4-9d0a-de60c49ce32d.png)
![image](https://user-images.githubusercontent.com/54863991/190463480-4079d839-3d7a-4b27-9adb-f68f253257c7.png)

**Additional context**
I've tried other outfit rules (ones revolving around specific names for outfits) and the do not work either.

**Comment by seppelinchen** [comment] 2022-09-17 10:37
i have exact the same issue with the same setup

**Comment by arkayenro** [comment] 2022-09-19 13:38
i'll try to sort out what the issue is when i get a chance

**Comment by arkayenro** [comment] 2022-09-29 14:16
fixed in 3.10.00 alpha 6

**Closed by arkayenro** 2022-09-29 14:16 UTC
Labels: bug, wrath
