### ISSUE TITLE
[BUG]  outfit() not working

### ISSUE THREAD

**Issue by leothlon** [arkayenro/arkinventory#1612] opened 2022-10-05 11:20 UTC
**What version number you are using?**
3.09.58

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
WOTLK classic

**What language is the game client set to?**
English

**Describe the bug**
rule "outfit()" and "outfit("DPS") does not work. i've tried with the built in equipment manager, outfitter and itemrack, it wont work with any of them.
i have also deleted my wtf folder trying to solve it. but nothing works
(yes, i have the rule assigned to a group AND i have enabled it)

it's the main reason i want arkinventory... prefferably if it would work with the built-in equipment manager, but tbh im happy if i can just get it to work at all or i might aswell go back to bagnon

**Comment by leothlon** [comment] 2022-10-05 11:30
i made a workaround by using the tooltip info : `tt( "Equipment Sets:" ) ` but altho this works, outfit() realy should work to

**Comment by arkayenro** [comment] 2022-10-05 12:34
duplicate of #1593 

fixed in 3.10.00 alpha 6

**Closed by arkayenro** 2022-10-05 12:34 UTC
