### ISSUE TITLE
Unable to load Ark inventory 3.06.07

### ISSUE THREAD

**Issue by jmredmon** [arkayenro/arkinventory#766] opened 2016-07-20 02:51 UTC
# Unable to open arkinventory, disclaimer i have lots of addons, but even with all disabled, it doesn't work

`2x ...rfaceArkInventoryRules\ArkInventoryRules-3.06.07.lua:86: attempt to index field 'db' (a nil value)
...rfaceArkInventoryRules\ArkInventoryRules-3.06.07.lua:86: in function <...rfaceArkInventoryRules\ArkInventoryRules.lua:81>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
AllPlayed\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
AllPlayed\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <AllPlayed\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: ?
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:391: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:482: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:993: in function <FrameXML\UIParent.lua:891>
[C]: ?

Locals:
nil`

# And

`5x ArkInventory\Locale\game-Game.lua:208: attempt to index field '?' (a nil value)
ArkInventory\Locale\game-Game.lua:208: in main chunk

Locals:
L = <table> {
}
ConvertToCapture = <function> defined @ArkInventory\Locale\game.lua:176
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = "WOW_ITEM_CLASS_WEAPON"
(*temporary) = nil
(*temporary) = "ItemClass"
(*temporary) = 132144
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 783
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
`

# And

`5x AceLocale-3.0-6: ArkInventory: Missing entry for 'WOW_ITEM_CLASS_MISC_JUNK'
ArkInventory\ArkInventory-3.06.06.lua:41: in main chunk

Locals:
nil`

# And

`5x ArkInventory\ArkInventoryConst.lua:20: Cannot find a library instance of "AceSerializer-3.0".
[C]: in function `error'
!Swatter\Support\LibStub.lua:23: in function `LibStub'
ArkInventory\ArkInventoryConst.lua:20: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "AceSerializer-3.0"."
`

# I'm getting the same errror for a few "entries"

`5x AceLocale-3.0-6: ArkInventory: Missing entry for 'WOW_ITEM_CLASS_GEM'
ArkInventory\ArkInventory-3.06.06.lua:112: in main chunk

Locals:
nil`

**Comment by jbresciani** [comment] 2016-07-20 04:15
I had to load the ace3 module as a stand alone module from the curse client to get rid of those errors

**Comment by jmredmon** [comment] 2016-07-20 04:20
That worked, thanks!
# 
Only error I'm seeing now is

1x ArkInventory\ArkInventoryRealms.lua:11: code failure
[C]: in function `assert'
ArkInventory\ArkInventoryRealms.lua:11: in function `addRealms'
ArkInventory\ArkInventoryRealms.lua:216: in main chunk

Locals:
(*temporary) = false
(*temporary) = "code failure"

**Comment by fencepost123** [comment] 2016-07-20 04:35
Just downloaded 3.06.08 and Ark is still not opening. Deleted interface and WTF folders and ark is only addon installed manually. When i click b to open bags the default wow bags open. When I mouse over the icon that shows latency and addon memory usage Ark is using memory but when I open interface inthe game menu the config menu is not there where it used to be in the addon panel. I installed Ace 3 seperately off curse as someone suggested and now Ark is opening I am going to try setting up now. If Ace 3 is the problem is it missing or not being accessed by Ark in the bundle

**Comment by arkayenro** [comment] 2016-07-20 05:39
i think ive worked out the serializer thing, should be fixed in .09

**Comment by arkayenro** [comment] 2016-07-20 05:50
fixed in .09

**Closed by arkayenro** 2016-07-20 05:50 UTC
Labels: bug
