### ISSUE TITLE
"outfit()" rule only works for sets created with Blizzard Equipment Manager if no other equipment management addons are present.

### ISSUE THREAD

**Issue by viliger2** [arkayenro/arkinventory#1605] opened 2022-09-29 19:49 UTC
**What version number you are using?**
3.09.68 & 3.10.00-alpha-6

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Wrath of the Lich King Classic

**What language is the game client set to?**
English

**Describe the bug**
"outfit()" rule only works for sets created with Blizzard Equipment Manager if no other equipment management addons are present.

**To Reproduce**
I've created a set in Blizzard Equipment Manager to use in a macro, created a rule for it in rule book, assigned it to a bar and it doesn't work if I have ItemRack enabled. If I disable it rules start to work.

**Screenshots**

**Additional context**
I've checked the code of the `function ArkInventoryRules.System.boolean_outfit( ... )` in `ArkInventoryRules.lua` and it returns the first possible result, depending on which addon is loaded
```
if IsAddOnLoaded( "Outfitter" ) and Outfitter:IsInitialized( ) then
	return ArkInventoryRules.System.boolean_outfit_outfitter( ... )
end

if IsAddOnLoaded( "ItemRack" ) then
	return ArkInventoryRules.System.boolean_outfit_itemrack( ... )
end

if IsAddOnLoaded( "GearQuipper" ) or IsAddOnLoaded( "GearQuipper-TBC" ) then
	return ArkInventoryRules.System.boolean_outfit_gearquipper( ... )
end

if C_EquipmentSet and C_EquipmentSet.CanUseEquipmentSets( ) then
	return ArkInventoryRules.System.boolean_outfit_blizzard( ... )
end

return false
```
If we are to slightly rewrite it to use separate value and then return it then it would work with multiple outfit addons. I know it is a niche use and I understand if the fix doesn't make it, but I would appreciate it.

**Comment by arkayenro** [comment] 2022-09-29 23:18
yeah, its easy to make them all work i could find a reason for someone to use more than one outfit mod

it wont hurt to make it cascade through them all though

**Comment by arkayenro** [comment] 2022-09-30 06:36
duplicate of #1578 (sort of)

**Comment by arkayenro** [comment] 2022-10-02 09:21
added to 3.10.00 alpha 7

**Closed by arkayenro** 2022-10-02 09:21 UTC
Labels: enhancement-request
