### ISSUE TITLE
Category Artefact Power not working

### ISSUE THREAD

**Issue by chintao** [arkayenro/arkinventory#874] opened 2016-09-27 18:08 UTC
is it just me? or does Ark Inventory don't sort Artefact Power since last Update?

**Comment by NeeFoo** [comment] 2016-09-28 09:56
Yeah, last update put all AP consumables in soulbound instead of AP category for me

**Comment by arkayenro** [comment] 2016-09-28 22:25
mine are under the artifact power category.

mouse over the items to confirm you dont have the retrieving item info issue as if the game doesnt return the tooltip for the item then i cant tell what it is

**Comment by chintao** [comment] 2016-09-28 23:21
nope, no tt bug. but i can't categorise them under "artefact power". have reinstalled the addon, but still not working.
![wowscrnshot_092916_012018](https://cloud.githubusercontent.com/assets/22480703/18935838/fe7bf6f2-85e2-11e6-8dad-dec9dd0afeeb.jpg)
![wowscrnshot_092916_012008](https://cloud.githubusercontent.com/assets/22480703/18935837/fe7a3f6a-85e2-11e6-95c5-03bd04b553c2.jpg)

**Comment by Xzygy** [comment] 2016-09-29 01:43
Confirming that I have the same problem.  This would have started in the last update (or in the last few days if there were multiple updates).

**Comment by arkayenro** [comment] 2016-09-29 03:56
ah, i just saw the screenshots.  somehow you have Rare as the second line, not Artifact Power.  the code only checks the second line as thats where it normally sits on mine with no mods.

the language in the screenshot looks like english but do you have a different base locale/language?

i'll change the scan to check the first 4 lines instead, that should pick it up

**Comment by chintao** [comment] 2016-09-29 15:16
y, i am from germany, but play with the english language. Thanks for your work =)

**Comment by MasterArnold** [comment] 2016-09-30 21:47
Same bug here
Im german with english client

![arkbug1](https://cloud.githubusercontent.com/assets/7779069/19007917/00862446-8768-11e6-831b-52be80927f06.png)
![arkbug2](https://cloud.githubusercontent.com/assets/7779069/19007916/008618de-8768-11e6-81dc-9e25f61bab96.png)

Version 3.07.09 works

**Comment by chintao** [comment] 2016-09-30 23:28
I found the Problem! It's the coloblind mode in the options that showes the rarity of the items. after deactivating it's working again, but i think it should be fixed for all the colorblind people out there ;)
![wowscrnshot_100116_012551](https://cloud.githubusercontent.com/assets/22480703/19009637/3d4f95de-8776-11e6-96ab-57852bf257cd.jpg)

**Comment by MasterArnold** [comment] 2016-10-01 11:31
I can confirm this fix
Thanks

**Comment by NeeFoo** [comment] 2016-10-01 12:37
Yup, disabling colorblind mode fixed it for me too.
Thanks!

**Comment by arkayenro** [comment] 2016-10-01 22:10
fixed in 30714

**Closed by arkayenro** 2016-10-01 22:10 UTC
Labels: bug

**Comment by sucht** [comment] 2017-01-30 02:52
i have the same problem, or maybe i am to stupid.

the tooltip of the artifact power consumable, they are greens/normal/not rare or something in this case, in question reads as follows:
1. (name of the consumable)
2. (artifact power)
3. (soulbound)

Artifact Power consumables are all put to the other Soulbound things, instead of the Artifact Power category.
