### ISSUE TITLE
Offlinemode stop working for the bag after some time.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [arkayenro/arkinventory#499] opened 2015-03-20 04:24 UTC
```
Downloaded from > curse


What steps will reproduce the problem?
1. Use  the addon for a set amount of time and when you chose to look at 
another characters there will only be a few items showing up.

What is the expected output? What do you see instead?
To show me what items i got on other characters.
Just a few items that never change.

What version of the product are you using? On what operating system?
3.02.87 Windows 7

Please provide any additional information below.

I have reinstalled the addon 2 times now and it will help, but i don´t want to 
keep doing that as its a pain to keep setting up all my rules and settings.
```

Original issue reported on code.google.com by `martin.d...@gmail.com` on 17 Jan 2012 at 2:26

**Comment by spiralofhope** [comment] 2015-10-12 08:52
This is a duplicate of #697

(well, it's the other way around but that issue has more conversation)

I recommend this issue be closed/duplicate

**Comment by arkayenro** [comment] 2016-07-07 10:46
closing old issues - if its still a problem re-open the ticket

**Closed by arkayenro** 2016-07-07 10:46 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
