### ISSUE TITLE
[BUG] outfit() does not work in wrath classic

### ISSUE THREAD

**Issue by rosenrusinov** [arkayenro/arkinventory#1608] opened 2022-10-03 06:25 UTC
**What version number you are using?**
![image](https://user-images.githubusercontent.com/5707996/193513099-1c3020d8-1bdd-423f-97f0-4118f07e253b.png)

**What game client are you playing? Retail, Burning Crusade, Classic / Live, PTR, Beta**
Wrath Classic

**What language is the game client set to?**
EN

**Describe the bug**
Using `outfit()` in any rule does not seem to have any effect

**To Reproduce**
1. Create a new rule with nothing else but `outfit()`
2. Assing rule to a category
3. Assing your items to an outfit
4. Observe that nothing happens

**Screenshots**
![image](https://user-images.githubusercontent.com/5707996/193513251-4ee26958-f830-43be-a6ca-dba969dfc3bf.png)
![image](https://user-images.githubusercontent.com/5707996/193513274-6188d36e-6cca-47f1-93e8-8877c5b3071c.png)

Item is in outfit set, but is sorting in Group 5 instead of Group 7, Rule is enabled

Rule category 7:
![image](https://user-images.githubusercontent.com/5707996/193513341-6e5356fd-7e44-4219-9562-9bfb4b8c9258.png)

Rule category 5:
![image](https://user-images.githubusercontent.com/5707996/193513384-fd39b0f8-ab61-4383-94c1-184ca05b566c.png)

**Additional context**

**Comment by arkayenro** [comment] 2022-10-03 09:43
duplicate of #1593

**Comment by arkayenro** [comment] 2022-10-03 09:43
its fixed in 3.10.00 alpha 6

**Closed by arkayenro** 2022-10-03 09:43 UTC
